generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tag
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tag
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, author]
      filter:
        display: ["quick edit search", author_id]
      form:    ~
      edit:
        display: [name, author_id, created_at, updated_at]
      new:
        display: [name, author_id]
