<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTagHierarchie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taghierarchies');
        $this->hasColumn('taghierarchie_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('hierarchie_level', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'area',
              1 => 'issue',
              2 => 'keyword',
             ),
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        $this->hasOne('TagHierarchie as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'taghierarchie_id'));

        $this->hasMany('Tag as Tags', array(
             'refClass' => 'TagHierarchieTag',
             'local' => 'taghierarchie_id',
             'foreign' => 'tag_id'));

        $this->hasMany('TagHierarchie as SubHierarchies', array(
             'local' => 'taghierarchie_id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}