<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTagimplications extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tagimplications');
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('implied_tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('implication_type', 'enum', 8, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'implies',
              1 => 'suggests',
             ),
             'notnull' => true,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Tags', array(
             'local' => 'implied_tag_id',
             'foreign' => 'tag_id'));

        $this->hasOne('Tags as Tags_2', array(
             'local' => 'tag_id',
             'foreign' => 'tag_id'));
    }
}