<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLegalValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('legal_values');
        $this->hasColumn('legal_value_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Document', array(
             'local' => 'legal_value_id',
             'foreign' => 'legal_value_id'));

        $this->hasMany('Documenttype', array(
             'local' => 'legal_value_id',
             'foreign' => 'legal_value_id'));
    }
}