<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOrganisations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organisations');
        $this->hasColumn('organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('parent_organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Organisations', array(
             'local' => 'parent_organisation_id',
             'foreign' => 'organisation_id'));

        $this->hasMany('Documents', array(
             'local' => 'organisation_id',
             'foreign' => 'organisation_id'));

        $this->hasMany('Memberstates2organisations', array(
             'local' => 'organisation_id',
             'foreign' => 'organsation_id'));

        $this->hasMany('Organisations as Organisations_1', array(
             'local' => 'organisation_id',
             'foreign' => 'parent_organisation_id'));

        $this->hasMany('Votingrecords', array(
             'local' => 'organisation_id',
             'foreign' => 'memberstate_id'));
    }
}