<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Clauses
 * @property Doctrine_Collection $Documents
 * @property Doctrine_Collection $ExcelFile
 * @property Doctrine_Collection $Document
 * @property Doctrine_Collection $ClauseBody
 * @property Doctrine_Collection $TagImplication
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method Doctrine_Collection getClauses()        Returns the current record's "Clauses" collection
 * @method Doctrine_Collection getDocuments()      Returns the current record's "Documents" collection
 * @method Doctrine_Collection getExcelFile()      Returns the current record's "ExcelFile" collection
 * @method Doctrine_Collection getDocument()       Returns the current record's "Document" collection
 * @method Doctrine_Collection getClauseBody()     Returns the current record's "ClauseBody" collection
 * @method Doctrine_Collection getTagImplication() Returns the current record's "TagImplication" collection
 * @method Tag                 setId()             Sets the current record's "id" value
 * @method Tag                 setName()           Sets the current record's "name" value
 * @method Tag                 setClauses()        Sets the current record's "Clauses" collection
 * @method Tag                 setDocuments()      Sets the current record's "Documents" collection
 * @method Tag                 setExcelFile()      Sets the current record's "ExcelFile" collection
 * @method Tag                 setDocument()       Sets the current record's "Document" collection
 * @method Tag                 setClauseBody()     Sets the current record's "ClauseBody" collection
 * @method Tag                 setTagImplication() Sets the current record's "TagImplication" collection
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClauseBody as Clauses', array(
             'refClass' => 'ClauseTag',
             'local' => 'tag_id',
             'foreign' => 'id'));

        $this->hasMany('Document as Documents', array(
             'refClass' => 'DocumentTag',
             'local' => 'tag_id',
             'foreign' => 'id'));

        $this->hasMany('ExcelFile', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $this->hasMany('Document', array(
             'refClass' => 'DocumentTag',
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('ClauseBody', array(
             'refClass' => 'ClauseTag',
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('TagImplication', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $blameable1 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0->addChild($blameable1);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($versionable0);
    }
}