<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTagImplication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tagimplications');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('implication_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'implies',
              1 => 'suggests',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('tag_left_hand', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tag_right_hand', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        $this->hasOne('Tag', array(
             'local' => 'tag_right_hand',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}