<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseVotingrecord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('votingrecords');
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('memberstate_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('vote_type', 'enum', 7, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'signed',
              1 => 'agreed',
              2 => 'no',
              3 => 'abstain',
              4 => 'missing',
             ),
             'notnull' => true,
             'length' => '7',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasOne('Organisation', array(
             'local' => 'memberstate_id',
             'foreign' => 'organisation_id'));
    }
}