<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseClause extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clauses');
        $this->hasColumn('clause_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('clause_number', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('parent_clause_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('information_type', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('operative_phrase', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('adressee', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('relevance', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('significants', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('content', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasOne('Clause', array(
             'local' => 'parent_clause_id',
             'foreign' => 'clause_id'));

        $this->hasMany('Tag as Tags', array(
             'refClass' => 'ClauseTag',
             'local' => 'clause_id',
             'foreign' => 'tag_id'));

        $this->hasMany('Clause as ParentClauses', array(
             'local' => 'clause_id',
             'foreign' => 'parent_clause_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}