<?php

/**
 * BaseDocumentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $legalvalue_id
 * @property integer $rank_priority
 * @property LegalValue $LegalValue
 * @property Doctrine_Collection $Documents
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getLegalvalueId()  Returns the current record's "legalvalue_id" value
 * @method integer             getRankPriority()  Returns the current record's "rank_priority" value
 * @method LegalValue          getLegalValue()    Returns the current record's "LegalValue" value
 * @method Doctrine_Collection getDocuments()     Returns the current record's "Documents" collection
 * @method DocumentType        setId()            Sets the current record's "id" value
 * @method DocumentType        setName()          Sets the current record's "name" value
 * @method DocumentType        setLegalvalueId()  Sets the current record's "legalvalue_id" value
 * @method DocumentType        setRankPriority()  Sets the current record's "rank_priority" value
 * @method DocumentType        setLegalValue()    Sets the current record's "LegalValue" value
 * @method DocumentType        setDocuments()     Sets the current record's "Documents" collection
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDocumentType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('legalvalue_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('rank_priority', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LegalValue', array(
             'local' => 'legalvalue_id',
             'foreign' => 'id'));

        $this->hasMany('Document as Documents', array(
             'local' => 'id',
             'foreign' => 'documenttype_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $blameable1 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0->addChild($blameable1);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($versionable0);
    }
}