<?php

/**
 * BaseCountryOrganisation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $join_date
 * @property date $leave_date
 * @property integer $country_id
 * @property integer $organisation_id
 * @property Country $Country
 * @property Organisation $Organisation
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method date                getJoinDate()        Returns the current record's "join_date" value
 * @method date                getLeaveDate()       Returns the current record's "leave_date" value
 * @method integer             getCountryId()       Returns the current record's "country_id" value
 * @method integer             getOrganisationId()  Returns the current record's "organisation_id" value
 * @method Country             getCountry()         Returns the current record's "Country" value
 * @method Organisation        getOrganisation()    Returns the current record's "Organisation" value
 * @method CountryOrganisation setId()              Sets the current record's "id" value
 * @method CountryOrganisation setJoinDate()        Sets the current record's "join_date" value
 * @method CountryOrganisation setLeaveDate()       Sets the current record's "leave_date" value
 * @method CountryOrganisation setCountryId()       Sets the current record's "country_id" value
 * @method CountryOrganisation setOrganisationId()  Sets the current record's "organisation_id" value
 * @method CountryOrganisation setCountry()         Sets the current record's "Country" value
 * @method CountryOrganisation setOrganisation()    Sets the current record's "Organisation" value
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCountryOrganisation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country_organisation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('join_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('leave_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('organisation_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasOne('Organisation', array(
             'local' => 'organisation_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'class' => 'sfGuardUser',
              'disabled' => false,
             ),
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $blameable1 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'class' => 'sfGuardUser',
              'disabled' => false,
             ),
             ));
        $versionable0->addChild($blameable1);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($versionable0);
    }
}