<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberstate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('memberstates');
        $this->hasColumn('memberstate_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Organisation as Organisations', array(
             'refClass' => 'MemberstateOrganisation',
             'local' => 'memberstate_id',
             'foreign' => 'organisation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}