<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documents');
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('documenttype_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('publication_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('adoption_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('code', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('legal_value', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('min_ratification_count', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('preamble', 'string', 60000, array(
             'type' => 'string',
             'length' => '60000',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Documenttype', array(
             'local' => 'documenttype_id',
             'foreign' => 'documenttype_id'));

        $this->hasOne('Organisation', array(
             'local' => 'organisation_id',
             'foreign' => 'organisation_id'));

        $this->hasMany('Tag as Tags', array(
             'refClass' => 'DocumentTag',
             'local' => 'document_id',
             'foreign' => 'tag_id'));

        $this->hasMany('Clause', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasMany('DocumentRelation', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasMany('Votingrecord', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}