<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseClause extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clauses');
        $this->hasColumn('clause_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('clause_process', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('clause_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('information_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('operative_phrase', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('addressee', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('relevance', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('significants', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('document_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Clause as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'clause_id'));

        $this->hasOne('ClauseProcess', array(
             'local' => 'clause_process',
             'foreign' => 'id'));

        $this->hasOne('ClauseInformationType', array(
             'local' => 'information_type',
             'foreign' => 'id'));

        $this->hasOne('ClauseOperativePhrase', array(
             'local' => 'operative_phrase',
             'foreign' => 'id'));

        $this->hasOne('Addressee', array(
             'local' => 'addressee',
             'foreign' => 'id'));

        $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasMany('Tag as Tags', array(
             'refClass' => 'ClauseTag',
             'local' => 'clause_id',
             'foreign' => 'tag_id'));

        $this->hasMany('Clause as Subclauses', array(
             'local' => 'clause_id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}