<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocumentType extends BaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documenttypes');
        $this->hasColumn('documenttype_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('legalvalue_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('LegalValue', array(
             'local' => 'legalvalue_id',
             'foreign' => 'legalvalue_id'));

        $this->hasMany('Document as Documents', array(
             'local' => 'documenttype_id',
             'foreign' => 'documenttype_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}