<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocument2tag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document2tag');
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Documents', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasOne('Tags', array(
             'local' => 'tag_id',
             'foreign' => 'tag_id'));
    }
}