# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  commentAdmin:
    max_length:     50
  vjCommentPlugin:
    guardbind: true
    restricted: true
  sfApplyPlugin:
    from:
      email: "noreply@un-informed.org"
      fullname: "UN-informed.org"
  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         UN-informed.org
    include_path:                 true
    include_jquery_no_conflict:   true
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout
    categories:
      "Documents/Clauses/Comments":
        credentials:      [admin]
        items:
          Documents:
            url:    document
          Clauses:
            url:    clause
          Comments:
            url:    commentAdmin
          Comment Reports:
            url:    commentReportAdmin
      "Reservations":
        credentials:      [admin]
        items:
          "Documents":
            url:    document_reservation
          "Clauses":
            url:    clause_reservation
      "Meta Data":
        credentials:      [admin]
        items:
          Votes:
            url:    vote
          Addressees:
            url:    addressee
          Organisations:
            url:    organisation
          "Excelfile Upload":
            url:    excel_file
      "User Management":
        credentials:      [superadmin]
        items:
          User:
            url:    sf_guard_user
          Groups:
            url:    sf_guard_group
          Permissions:
            url:    sf_guard_perm
