documenttypes_documenttypes:
  class: sfDoctrineRouteCollection
  options:
    model:                Documenttypes
    module:               documenttypes
    prefix_path:          documenttypes
    column:               documenttype_id
    with_wildcard_routes: true

tags_tags:
  class: sfDoctrineRouteCollection
  options:
    model:                Tags
    module:               tags
    prefix_path:          tags
    column:               tag_id
    with_wildcard_routes: true

organisations_organisations:
  class: sfDoctrineRouteCollection
  options:
    model:                Organisations
    module:               organisations
    prefix_path:          organisations
    column:               organisation_id
    with_wildcard_routes: true

documents_documents:
  class: sfDoctrineRouteCollection
  options:
    model:                Documents
    module:               documents
    prefix_path:          documents
    column:               document_id
    with_wildcard_routes: true

clauses_clauses:
  class: sfDoctrineRouteCollection
  options:
    model:                Clauses
    module:               clauses
    prefix_path:          clauses
    column:               clause_id
    with_wildcard_routes: true

memberstates_memberstates:
  class: sfDoctrineRouteCollection
  options:
    model:                Memberstates
    module:               memberstates
    prefix_path:          memberstates
    column:               memberstate_id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
