legal_value_legalvalues:
  class: sfDoctrineRouteCollection
  options:
    model:                LegalValue
    module:               legalvalues
    prefix_path:          legalvalues
    column:               legal_value_id
    with_wildcard_routes: true

organisation_organisations:
  class: sfDoctrineRouteCollection
  options:
    model:                Organisation
    module:               organisations
    prefix_path:          organisations
    column:               organisation_id
    with_wildcard_routes: true

memberstate_memberstates:
  class: sfDoctrineRouteCollection
  options:
    model:                Memberstate
    module:               memberstates
    prefix_path:          memberstates
    column:               memberstate_id
    with_wildcard_routes: true

documenttype_documenttypes:
  class: sfDoctrineRouteCollection
  options:
    model:                Documenttype
    module:               documenttypes
    prefix_path:          documenttypes
    column:               documenttype_id
    with_wildcard_routes: true

document_documents:
  class: sfDoctrineRouteCollection
  options:
    model:                Document
    module:               documents
    prefix_path:          documents
    column:               document_id
    with_wildcard_routes: true

clause_clauses:
  class: sfDoctrineRouteCollection
  options:
    model:                Clause
    module:               clauses
    prefix_path:          clauses
    column:               clause_id
    with_wildcard_routes: true

tag_tags:
  class: sfDoctrineRouteCollection
  options:
    model:                Tag
    module:               tags
    prefix_path:          tags
    column:               tag_id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: documents, action: index }

# default rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
