<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseClauseAddressee extends BaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clause_addressee');
        $this->hasColumn('clause_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('addressee_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}