<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocumentRelation extends BaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentrelations');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('relation_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'followup',
              1 => 'recalls',
              2 => 'report',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('document_left_hand', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('document_right_hand', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Document', array(
             'local' => 'document_right_hand',
             'foreign' => 'document_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}