<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberstate extends BaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('memberstates');
        $this->hasColumn('memberstate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('MemberstateOrganisation as Organisations', array(
             'local' => 'memberstate_id',
             'foreign' => 'memberstate_id'));

        $this->hasMany('Vote as Votes', array(
             'local' => 'memberstate_id',
             'foreign' => 'memberstate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}