<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOrganisation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organisations');
        $this->hasColumn('organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('parent_organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Memberstate as Memberstates', array(
             'refClass' => 'MemberstateOrganisation',
             'local' => 'organisation_id',
             'foreign' => 'memberstate_id'));

        $this->hasMany('Organisation as ChildOrganisations', array(
             'local' => 'organisation_id',
             'foreign' => 'parent_organisation_id'));

        $this->hasMany('Votingrecord', array(
             'local' => 'organisation_id',
             'foreign' => 'memberstate_id'));

        $this->hasMany('Document', array(
             'local' => 'organisation_id',
             'foreign' => 'organisation_id'));

        $this->hasOne('Organisation', array(
             'local' => 'parent_organisation_id',
             'foreign' => 'organisation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}