<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTagHierarchieTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taghierarchie2tag');
        $this->hasColumn('taghierarchie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
    }

}