<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberstateOrganisation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('memberstates2organisations');
        $this->hasColumn('memberstate_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('month', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
    }

}