<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberstateOrganisation extends BaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('memberstatesorganisations');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('join_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('leave_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('memberstate_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organisation_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Memberstate', array(
             'local' => 'memberstate_id',
             'foreign' => 'memberstate_id'));

        $this->hasOne('Organisation', array(
             'local' => 'organisation_id',
             'foreign' => 'organisation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}