<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocumenttypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documenttypes');
        $this->hasColumn('documenttype_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('legal_value', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Documents', array(
             'local' => 'documenttype_id',
             'foreign' => 'documenttype_id'));
    }
}