<?php

/**
 * BaseDocumentDocumentRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $type
 * @property integer $document_id
 * @property integer $related_document_id
 * @property Document $Document
 * @property Document $DocumentRelated
 * 
 * @method integer                  getId()                  Returns the current record's "id" value
 * @method enum                     getType()                Returns the current record's "type" value
 * @method integer                  getDocumentId()          Returns the current record's "document_id" value
 * @method integer                  getRelatedDocumentId()   Returns the current record's "related_document_id" value
 * @method Document                 getDocument()            Returns the current record's "Document" value
 * @method Document                 getDocumentRelated()     Returns the current record's "DocumentRelated" value
 * @method DocumentDocumentRelation setId()                  Sets the current record's "id" value
 * @method DocumentDocumentRelation setType()                Sets the current record's "type" value
 * @method DocumentDocumentRelation setDocumentId()          Sets the current record's "document_id" value
 * @method DocumentDocumentRelation setRelatedDocumentId()   Sets the current record's "related_document_id" value
 * @method DocumentDocumentRelation setDocument()            Sets the current record's "Document" value
 * @method DocumentDocumentRelation setDocumentRelated()     Sets the current record's "DocumentRelated" value
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseDocumentDocumentRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document_document_relation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'followup',
              1 => 'recalls',
              2 => 'closely_related',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('related_document_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('mapping', array(
             'fields' => 
             array(
              0 => 'document_id',
              1 => 'related_document_id',
              2 => 'type',
             ),
             'type' => 'unique',
             ));
        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'id'));

        $this->hasOne('Document as DocumentRelated', array(
             'local' => 'related_document_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              'options' => 
              array(
               'notnull' => false,
              ),
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $blameable1 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              'options' => 
              array(
               'notnull' => false,
              ),
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0->addChild($blameable1);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($versionable0);
    }
}