<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tags');
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('tag_type', 'enum', 13, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'legal_measure',
             ),
             'length' => '13',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Clause as Clauses', array(
             'refClass' => 'ClauseTag',
             'local' => 'tag_id',
             'foreign' => 'clause_id'));

        $this->hasMany('Document as Documents', array(
             'refClass' => 'DocumentTag',
             'local' => 'tag_id',
             'foreign' => 'document_id'));

        $this->hasMany('TagHierarchie as TagHierarchies', array(
             'refClass' => 'TagHierarchieTag',
             'local' => 'tag_id',
             'foreign' => 'taghierarchie_id'));

        $this->hasMany('TagImplication as ImpliedTagImplications', array(
             'local' => 'tag_id',
             'foreign' => 'implied_tag_id'));

        $this->hasMany('TagImplication as Tagimplications', array(
             'local' => 'tag_id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}