<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTagHierarchie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taghierarchies');
        $this->hasColumn('taghierarchie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('hierachie_level', 'enum', 7, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'area',
              1 => 'issue',
              2 => 'keyword',
             ),
             'notnull' => true,
             'length' => '7',
             ));
        $this->hasColumn('parent_taghierarchie_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Tag as Tags', array(
             'refClass' => 'TagHierarchieTag',
             'local' => 'taghierarchie_id',
             'foreign' => 'tag_id'));
    }
}