<?php

/**
 * BaseClauseClauseRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $type
 * @property integer $clause_id
 * @property integer $related_clause_id
 * @property Clause $Clause
 * @property Clause $ClauseRelated
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method enum                 getType()              Returns the current record's "type" value
 * @method integer              getClauseId()          Returns the current record's "clause_id" value
 * @method integer              getRelatedClauseId()   Returns the current record's "related_clause_id" value
 * @method Clause               getClause()            Returns the current record's "Clause" value
 * @method Clause               getClauseRelated()     Returns the current record's "ClauseRelated" value
 * @method ClauseClauseRelation setId()                Sets the current record's "id" value
 * @method ClauseClauseRelation setType()              Sets the current record's "type" value
 * @method ClauseClauseRelation setClauseId()          Sets the current record's "clause_id" value
 * @method ClauseClauseRelation setRelatedClauseId()   Sets the current record's "related_clause_id" value
 * @method ClauseClauseRelation setClause()            Sets the current record's "Clause" value
 * @method ClauseClauseRelation setClauseRelated()     Sets the current record's "ClauseRelated" value
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseClauseClauseRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clause_clause_relation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'recalls',
              1 => 'closely_related',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('clause_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('related_clause_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('mapping', array(
             'fields' => 
             array(
              0 => 'clause_id',
              1 => 'related_clause_id',
              2 => 'type',
             ),
             'type' => 'unique',
             ));
        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clause', array(
             'local' => 'clause_id',
             'foreign' => 'id'));

        $this->hasOne('Clause as ClauseRelated', array(
             'local' => 'related_clause_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              'options' => 
              array(
               'notnull' => false,
              ),
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $blameable1 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              'options' => 
              array(
               'notnull' => false,
              ),
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $versionable0->addChild($blameable1);
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($versionable0);
    }
}