<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberstates2organisations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('memberstates2organisations');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('memberstate_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('organsation_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('from_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('to_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Memberstates', array(
             'local' => 'memberstate_id',
             'foreign' => 'memberstate_id'));

        $this->hasOne('Organisations', array(
             'local' => 'organsation_id',
             'foreign' => 'organisation_id'));
    }
}