<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocumentrelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentrelations');
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('related_document_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('relation_type', 'enum', 8, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'followup',
              1 => 'recalls',
              2 => 'report',
             ),
             'primary' => true,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Documents', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasOne('Documents as Documents_2', array(
             'local' => 'related_document_id',
             'foreign' => 'document_id'));
    }
}