<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDocuments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documents');
        $this->hasColumn('document_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('documenttype_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('legal_value', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('organisation_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('adoption_date', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('code', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('min_ratification_count', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('preamble', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Documenttypes', array(
             'local' => 'documenttype_id',
             'foreign' => 'documenttype_id'));

        $this->hasOne('Organisations', array(
             'local' => 'organisation_id',
             'foreign' => 'organisation_id'));

        $this->hasMany('Clauses', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasMany('Document2tag', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasMany('Documentrelations', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasMany('Documentrelations as Documentrelations_2', array(
             'local' => 'document_id',
             'foreign' => 'related_document_id'));

        $this->hasMany('Votingrecords', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));
    }
}