<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTaghierachies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taghierachies');
        $this->hasColumn('taghierarchie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('hierachie_level', 'enum', 7, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'area',
              1 => 'issue',
              2 => 'keyword',
             ),
             'notnull' => true,
             'length' => '7',
             ));
        $this->hasColumn('parent_taghierachie_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Taghierachies', array(
             'local' => 'parent_taghierachie_id',
             'foreign' => 'taghierarchie_id'));

        $this->hasMany('Taghierachie2tag', array(
             'local' => 'taghierarchie_id',
             'foreign' => 'taghierachie_id'));

        $this->hasMany('Taghierachies as Taghierachies_1', array(
             'local' => 'taghierarchie_id',
             'foreign' => 'parent_taghierachie_id'));
    }
}