<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseClause2tag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clause2tag');
        $this->hasColumn('clause_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Clauses', array(
             'local' => 'clause_id',
             'foreign' => 'clause_id'));

        $this->hasOne('Tags', array(
             'local' => 'tag_id',
             'foreign' => 'tag_id'));
    }
}