<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $Documents
 * @property Doctrine_Collection $ClauseBodies
 * @property Doctrine_Collection $TagImplication
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method clob                getDescription()    Returns the current record's "description" value
 * @method Doctrine_Collection getDocuments()      Returns the current record's "Documents" collection
 * @method Doctrine_Collection getClauseBodies()   Returns the current record's "ClauseBodies" collection
 * @method Doctrine_Collection getTagImplication() Returns the current record's "TagImplication" collection
 * @method Tag                 setId()             Sets the current record's "id" value
 * @method Tag                 setName()           Sets the current record's "name" value
 * @method Tag                 setDescription()    Sets the current record's "description" value
 * @method Tag                 setDocuments()      Sets the current record's "Documents" collection
 * @method Tag                 setClauseBodies()   Sets the current record's "ClauseBodies" collection
 * @method Tag                 setTagImplication() Sets the current record's "TagImplication" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends MyBaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));


        $this->index('name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Document as Documents', array(
             'refClass' => 'DocumentTag',
             'local' => 'tag_id',
             'foreign' => 'document_id'));

        $this->hasMany('ClauseBody as ClauseBodies', array(
             'refClass' => 'ClauseBodyTag',
             'local' => 'tag_id',
             'foreign' => 'clause_body_id'));

        $this->hasMany('TagImplication', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'id',
             'listener' => 'BlameableCustomListener',
             'columns' => 
             array(
              'created' => 
              array(
              'name' => 'author_id',
              'length' => 4,
              'options' => 
              array(
               'notnull' => false,
              ),
              ),
              'updated' => 
              array(
              'disabled' => true,
              ),
             ),
             'relations' => 
             array(
              'created' => 
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
    }
}