generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ExcelFile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          excel_file
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, created_at, updated_at, author]
        object_actions:
          _edit: ~
          _delete: ~  
          import: { label: Import, action: excelSpreadsheetImport}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
