generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Organisation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organisation_organisations
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        organisation: { label: "Parent organisation" }
        parent_organisation_id: { label: "Parent organisation" }
      list:
        display: [=name, organisation]
      filter:  ~
      form:    ~
      edit:
        display: [name, parent_organisation_id, memberstates_list, created_at, updated_at]
      new:
        display: [name, parent_organisation_id, memberstates_list]
