generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Document
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          document_documents
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        documenttype_id: { label: Document type}
        organisation_id: { label: Organisation}
        legal_value_id: { label: Legal value}
      list:
        display: [=name, documenttype, organisation]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
