<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddresseeTable extends Doctrine_Table
{
  public function getAllAddressees()
  {
    $q = $this->createQuery('j');
    return $q->fetchArray();
  }
  
  public function getAllAddresseeNames()
  {
    $q = $this->createQuery('a')
      ->select('a.name');
      
     return $q->fetchArray();
  }
  
  public function retrieveAddresseeIdByName($addresseeName)
  {
    $addressees = $this->getAllAddressees();
    
    foreach($addressees as $addressee)
    {
      //case insensitive comparison
      $compareResult = strcasecmp($addresseeName, $addressee['name']);
      if($compareResult == 0)
      {
        return $addressee['id'];
      }
    }
    
    return NULL;
  }
}