<?php

/**
 * Clause
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Clause extends BaseClause
{
    public function preSave($event) {
        $invoker = $event->getInvoker();
        $clauseOrdering = $invoker->_get('Document')->_get('clause_ordering');

        $slug = $invoker->_get('Document')->_get('code');
        $slug.= ' '.$invoker->_get('clause_body_id');
        $slug.= ' '.(str_word_count($clauseOrdering, 0, '023456789')+1);
        $slug.= ' '.$invoker->_get('clause_number_information');
        $slug.= ' '.$invoker->_get('clause_number_subparagraph');
        $slug = Doctrine_Inflector::urlize($slug);
        $invoker->_set('slug', $slug);
    }

    public function postSave($event) {
        $invoker = $event->getInvoker();

        $id = $invoker->_get('id');
        $clauseOrdering = $invoker->_get('Document')->_get('clause_ordering');
        if (!preg_match("/(^|,)$id(,|$)/", $clauseOrdering)) {
            Doctrine_Query::create()
                ->update('Document')
                ->set('clause_ordering', "IF (clause_ordering IS NULL, '$id', CONCAT (clause_ordering, ',$id'))")
                ->where('id = ?', $invoker->_get('Document')->_get('id'))
                ->execute();
        }
        $invoker->_get('Document')->refresh();
    }

    public function getSlug() {
        return $this->_get('id').'-'.$this->_get('slug');
    }
}