<?php

/**
 * ClauseBody
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ClauseBody extends BaseClauseBody
{
    public function setUp()
    {
        parent::setUp();
        $this->hasAccessor('root_clause_body_id', 'getRootClauseBodyId');
    }

    public function getRootClauseBodyId() {
        $root_clause_body_id = $this->_get('root_clause_body_id');
        return empty($root_clause_body_id) ? $this->_get('id') : $root_clause_body_id;
    }

    public function preSave($event) {
        $invoker = $event->getInvoker();

        $root_clause_body_id = $invoker->_get('root_clause_body_id');
        $parent_clause_body_id = $invoker->_get('parent_clause_body_id');
        if (!empty($parent_clause_body_id) && empty($root_clause_body_id)) {
            $root_clause_body_id = $invoker->ClauseBodyParent->root_clause_body_id;
            $invoker->set('root_clause_body_id', $root_clause_body_id);
        }
    }

    public function getContent() {
        $operative_phrase = (string)$this->_get('ClauseOperativePhrase');
        return preg_replace('#\b('.preg_quote($operative_phrase, '#').')\b#i', '<em>$1</em>', $this->_get('content'));
    }

    public function __toString() {
        $clause = Doctrine_Query::create()
            ->from('Clause c')
            ->where('c.clause_body_id = ?', array($this->_get('id')))
            ->fetchOne();

        if (empty($clause)) {
            return null;
        }

        return (string)$clause->getLatestAdoptedClause();
    }
}
