<?php

/**
 * Clause
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Clause extends BaseClause
{
    protected static $autoCompletable = array(
        'slug' => true,
    );

    public function __toString() {
        $identifier = (string)$this->_get('Document');
        $identifier.= ' #'.$this->_get('clause_number');
        if ($this->_get('clause_number_information')) {
            $identifier.= ' '.$this->_get('clause_number_information');
        }
        if ($this->_get('clause_number_subparagraph')) {
            $identifier.= ' '.$this->_get('clause_number_subparagraph');
        }
        if ($this->_get('ClauseBody')->_get('ClauseInformationType')) {
            $identifier.= ' '.$this->_get('ClauseBody')->_get('ClauseInformationType')->_get('name');
        }
        return trim($identifier);
    }

    public function preSave($event) {
        if (!$this->exists()) {
            $invoker = $event->getInvoker();
            $clauseOrdering = $invoker->_get('Document')->_get('clause_ordering');

            $invoker->_set('clause_number', (str_word_count($clauseOrdering, 0, '0123456789')+1));

            $slug = (string)$invoker;
            $slug = Doctrine_Inflector::urlize($slug);
            $invoker->_set('slug', $slug);
        }
    }

    public function postSave($event) {
        $invoker = $event->getInvoker();

        $id = $invoker->_get('id');
        $clauseOrdering = $invoker->_get('Document')->_get('clause_ordering');
        if (!preg_match("/(^|,)$id(,|$)/", $clauseOrdering)) {
            Doctrine_Query::create()
                ->update('Document')
                ->set('clause_ordering', "IF (clause_ordering IS NULL, '$id', CONCAT (clause_ordering, ',$id'))")
                ->where('id = ?', $invoker->_get('Document')->_get('id'))
                ->execute();
        }
        $invoker->_get('Document')->refresh();
    }

    public function getTitle() {
        return $this->_get('Document')->_get('name').' ('.(string)$this.')';
    }

    public function getDocumenttypeId() {
        return $this->_get('Document')->_get('documenttype_id');
    }

    public function getOrganisationId() {
        return $this->_get('Document')->_get('organisation_id');
    }

    public function getLegalValueId() {
        return $this->_get('Document')->getLegalValueId();
    }

    public function getDecisionType() {
        return $this->_get('Document')->getDecisionType();
    }

    public function getAdoptionDate() {
        $adoption_date = $this->_get('Document')->_get('adoption_date');
        return date('Y-m-d\TH:i:s\Z', strtotime($adoption_date));
    }

    public function getSlug() {
        return $this->_get('id').'-'.$this->_get('slug');
    }

    public function getClausesByRoot() {
        $root_clause_body_id = $this->ClauseBody->root_clause_body_id;
        $query = Doctrine_Query::create()
            ->from('Clause c INDEXBY c.document_id')
            ->innerJoin('c.ClauseBody cb')
            ->where('cb.id = ? OR cb.root_clause_body_id = ?', array($root_clause_body_id, $root_clause_body_id));

        return $query->execute();
    }
}
