<?php

/**
 * DocumentType
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class DocumentType extends BaseDocumentType
{
    public function getDecisionType() {
        return $this->_get('LegalValue')->_get('decision_type');
    }
}
