<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentTypeTable extends Doctrine_Table
{
  public function getAllDocumentTypes()
  {
    $q = $this->createQuery('j');
    return $q->fetchArray();
  }
  
  public function retrieveDocumentTypeIdByName($documentTypeName)
  {
    $documentTypes = $this->getAllDocumentTypes();
    
    foreach($documentTypes as $documentType)
    {
      if($documentTypeName == $documentType['name'])
      {
        return $documentType['documenttype_id'];
      }
    }
    
    return NULL;
  }
}