<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganisationTable extends Doctrine_Table
{
  public function getAllOrganisations()
  {
    $q = $this->createQuery('j');
    return $q->fetchArray();
  }
  
  /**
   * Returns the id of the first organisation object with its name matching
   * the actual name string from the delivered array of organisation names.
   * Otherwise returns NULL.
   * 
   * @param $organisationNames
   * @return unknown_type
   */
  public function retrieveOrganisationIdByOrganisationNames($organisationNames)
  {
    $organisations = $this->getAllOrganisations();
    
    for($i = 0; $i < count($organisationNames); $i++)
    {
      foreach($organisations as $organisation)
      {
        if($organisation['name'] == $organisationNames[$i])
        {
          return $organisation['organisation_id'];
        }
      }
    }
    
    return NULL;
  }
}