<?php

/**
 * Vote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Vote extends BaseVote
{
    public function retrieveDocumentReservation()
    {
        $q = Doctrine_Query::create()
            ->select("dr.id, dr.reservation")
            ->from('DocumentReservation dr')
            ->where('dr.document_id = ?', $this->_get('document_id'))
            ->andWhere('dr.country_id = ?', $this->_get('country_id'));

        return $q->fetchOne();
    }
}
