<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    public function setUp()
    {
        parent::setUp();

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $blameable0 = new Doctrine_Template_Blameable(array(
             'default' => NULL,
             'blameVar' => 'user_id',
             'listener' => 'BlameableCustomListener',
             'columns' =>
             array(
              'created' =>
              array(
              'name' => 'author_id',
              'length' => 4,
              'options' =>
              array(
                'notnull' => false,
              )
              ),
              'updated' =>
              array(
              'disabled' => true,
              ),
             ),
             'relations' =>
             array(
              'created' =>
              array(
              'class' => 'sfGuardUser',
              'disabled' => false,
              'name' => 'Author',
              ),
             ),
             ));
        $this->actAs($softdelete0);
        $this->actAs($blameable0);
    }
}
