generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Organisation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organisation_organisations
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Organisations
        display: [name, parent]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
