# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    etag:                   false

all:
  .settings:
    no_script_name:         true
    check_lock:    true

    i18n: on

    # Form security secret (CSRF protection)
    csrf_secret:            f47b180fef6758817dd77d94bf2c3342d8c1c43f

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    enabled_modules:      [default, sfGuardAuth, sfApply, sfLucene, comment]

    sf_guard_plugin:
      routes_register: false

    sf_guard_extra_plugin:
      from:   noreply@resolutionfinder.org

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure

  .actions:
    error_404_module: default   # To be called when a 404 error is raised
    error_404_action: error404   # Or when the requested URL doesn't match any route
    module_disabled_module: default   # To be called when a user requests
    module_disabled_action: error404
