# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title: UN-informed.org
    description:  UN-informed.org is a project of MCM, providing a structured database for UN resolutions
    keywords:     UN, resolutions
    language:     en
    robots:       index, follow

  stylesheets:    ["main.css", "smoothness/jquery-ui-1.8.custom.css"]

  javascripts:
    - jquery-1.4.2.min.js
    - jquery-ui-1.8.custom.min.js
    - jquery.jqote2.js
    - main.js

  has_layout:     true
  layout:         layout
