<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseVote extends BaseRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('votes');
        $this->hasColumn('vote_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('label', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'signed',
              1 => 'agreed',
              2 => 'no',
              3 => 'abstain',
              4 => 'missing',
             ),
             ));
        $this->hasColumn('document_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('memberstate_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collation', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'document_id'));

        $this->hasOne('Memberstate', array(
             'local' => 'memberstate_id',
             'foreign' => 'memberstate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}