<?php

/**
 * ClauseClauseRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class ClauseClauseRelation extends BaseClauseClauseRelation
{
    protected $post_delete_data;

    public function postSave($event) {
        $invoker = $event->getInvoker();
        if ($invoker->_get('type') === 'closely related') {
            $reverse = Doctrine_Query::create()
                ->from('ClauseClauseRelation')
                ->where('clause_id = ? AND related_clause_id = ?', array($invoker->_get('related_clause_id'), $invoker->_get('clause_id')))
                ->fetchOne();
            if (!$reverse) {
                $reverse = new ClauseClauseRelation();
                $reverse->set('clause_id', $invoker->_get('related_clause_id'));
                $reverse->set('related_clause_id', $invoker->_get('clause_id'));
                $reverse->set('type', $invoker->_get('type'));
                $reverse->save();
            }
        }
    }

    public function preDelete($event) {
        $invoker = $event->getInvoker();
        if ($invoker->_get('type') === 'closely related') {
            $this->post_delete_data['clause_id'] = $invoker->_get('related_clause_id');
            $this->post_delete_data['related_clause_id'] = $invoker->_get('clause_id');
            $this->post_delete_data['type'] = $invoker->_get('type');
        }
    }

    public function postDelete($event) {
        if (!empty($this->post_delete_data)) {
            $reverse = Doctrine_Query::create()
                ->from('ClauseClauseRelation')
                ->where('clause_id = ? AND related_clause_id = ? AND type = ?', array($this->post_delete_data['clause_id'], $this->post_delete_data['related_clause_id'] , $this->post_delete_data['type']))
                ->fetchOne();
            if ($reverse) {
                $reverse->delete();
            }
        }
        unset($this->post_delete_data);
    }
}
