<?php

/**
 * DocumentDocumentRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class DocumentDocumentRelation extends BaseDocumentDocumentRelation
{
    protected $post_delete_data;

    public function postSave($event) {
        $invoker = $event->getInvoker();
        if ($invoker->_get('type') === 'closely related') {
            $reverse = Doctrine_Query::create()
                ->from('DocumentDocumentRelation')
                ->where('document_id = ? AND related_document_id = ?', array($invoker->_get('related_document_id'), $invoker->_get('document_id')))
                ->fetchOne();
            if (!$reverse) {
                $reverse = new DocumentDocumentRelation();
                $reverse->set('document_id', $invoker->_get('related_document_id'));
                $reverse->set('related_document_id', $invoker->_get('document_id'));
                $reverse->set('type', $invoker->_get('type'));
                $reverse->save();
            }
        }
    }

    public function preDelete($event) {
        $invoker = $event->getInvoker();
        if ($invoker->_get('type') === 'closely related') {
            $this->post_delete_data['document_id'] = $invoker->_get('related_document_id');
            $this->post_delete_data['related_document_id'] = $invoker->_get('document_id');
            $this->post_delete_data['type'] = $invoker->_get('type');
        }
    }

    public function postDelete($event) {
        if (!empty($this->post_delete_data)) {
            $reverse = Doctrine_Query::create()
                ->from('DocumentDocumentRelation')
                ->where('document_id = ? AND related_document_id = ? AND type = ?', array($this->post_delete_data['document_id'], $this->post_delete_data['related_document_id'] , $this->post_delete_data['type']))
                ->fetchOne();
            if ($reverse) {
                $reverse->delete();
            }
        }
        unset($this->post_delete_data);
    }
}
