generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Addressee
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              addressee
    plural:                addressee
    route_prefix:          addressee
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, numberAddressedClauses]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [name, document]
        fields:
          document:
            label: Filter by Document
            help: Type the document code you want to filter by
      form:    ~
      edit:    ~
      new:     ~
