generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Vote
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              vote
    plural:                votes
    route_prefix:          vote
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [type, document, country]
      filter:  ~
      form:    ~
      edit:
        display: [document_id, country_id, type]
      new:
        display: [document_id, country_id, type]
