generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tag
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tag_tags
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        tag_type: { label: Type}
      list:
        display: [=name, tag_type]
      filter:  ~
      form:    ~
      edit:
        display: [name, tag_type, created_at, updated_at]
      new:     ~
