generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Memberstate
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          memberstate_memberstates
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name]
      filter:  ~
      form:    ~
      edit:
        display: [name, organisations_list, created_at, updated_at]
        fields:
          organisations_list: { label: Organisations }
      new:     ~
