<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('clause_body', 'is_latest_clause_body');
        $this->addColumn('clause', 'is_latest_clause', 'boolean', '1', array(
             'default' => '1',
             ));
    }

    public function postUp()
    {
        $q = Doctrine_Query::create()
            ->from('Clause c')
            ->innerJoin('c.ClauseBody cb')
            ->where('cb.root_clause_body_id IS NULL');
        $result = $q->execute(array(), Doctrine_Core::HYDRATE_ON_DEMAND);
        foreach ($result as $obj) {
            $obj->forceIsLatestClauseUpdate();
        }
    }

    public function down()
    {
        $this->addColumn('clause_body', 'is_latest_clause_body', 'boolean', '1', array(
             'default' => '1',
             ));
        $this->removeColumn('clause', 'is_latest_clause');
    }

    public function postDown()
    {
        // migrate data
    }
}
