generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DocumentType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          document_type_documenttypes
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Document Types Management
        display: [name]
      filter:  ~
      form:    ~
      edit:
        title: Edit Document type "%%name%%"
      new:
        title: Create new Document Type
