ClauseBody:
  index:
    cultures: [en]
    encoding: UTF-8
    host: 127.0.0.1
    port: 8983
    base_url: "/solr"
  models:
    ClauseBody:
      validator: isIndexable
      fields:
        id:
          type: int
          indexed: false
          stored: true
          required: true
          alias: getId
        clause_id:
          type: int
          required: true
          stored: true
          alias: getClauseId
        is_latest_clause_body:
          type: boolean
          required: true
          alias: getIsLatestClauseBody
        title:
          type: text
          alias: getTitle
          stored: true
        adoption_date:
          type: tdate
          stored: false
          alias: getAdoptionDate
        tag_ids:
          type: int
          stored: false
          multiValued: true
          alias: getTagIds
          boost: 2
        addressee_ids:
          type: int
          stored: false
          multiValued: true
          alias: getAddresseeIds
        content:
          type: text
          stored: true
          alias: getContent
        documenttype_id:
          type: int
          stored: false
          alias: getDocumenttypeId
        operative_phrase_id:
          type: int
          stored: false
          alias: getOperativePhraseId
        information_type_id:
          type: int
          stored: false
          alias: getInformationTypeId
        organisation_id:
          type: int
          stored: false
          alias: getOrganisationId
        legal_value:
          type: string
          stored: false
          alias: getLegalValue
