Clause:
  index:
    cultures: [en]
    encoding: UTF-8
    host: 127.0.0.1
    port: 8983
    base_url: "/solr"
  models:
    Clause:
      fields:
        id:
          type: int
          indexed: false
          stored: true
          required: true
        is_latest_clause:
          type: boolean
          required: true
        document_title:
          type: text
          stored: true
        adoption_year:
          type: int
        tag_ids:
          type: int
          multiValued: true
          boost: 2
        addressee_ids:
          type: int
          multiValued: true
        content:
          type: text
          stored: true
        documenttype_id:
          type: int
        operative_phrase_id:
          type: int
        information_type_id:
          type: int
        organisation_id:
          type: int
          alias: getOrganisationIdSolr
        legal_value:
          type: string
