<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/08/22 14:59:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=uninformed',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
