<?php

/**
 * ClauseBody
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ClauseBody extends BaseClauseBody
{
    protected static $autoCompletable = array(
        'content' => true,
    );

    public function setUp()
    {
        parent::setUp();
        $this->hasAccessor('root_clause_body_id', 'getRootClauseBodyId');
    }

    public function getRootClauseBodyId() {
        $root_clause_body_id = $this->_get('root_clause_body_id');
        return empty($root_clause_body_id) ? $this->_get('id') : $root_clause_body_id;
    }

    public function preSave($event) {
        $invoker = $event->getInvoker();

        $root_clause_body_id = $invoker->_get('root_clause_body_id');
        $parent_clause_body_id = $invoker->_get('parent_clause_body_id');
        if (!empty($parent_clause_body_id) && empty($root_clause_body_id)) {
            $root_clause_body_id = $invoker->ClauseBodyParent->root_clause_body_id;
            $invoker->set('root_clause_body_id', $root_clause_body_id);
        }
    }

    public static function applyOperativePhraseToContent($content, $operative_phrase)
    {
        return preg_replace('#\b('.preg_quote($operative_phrase, '#').')\b#i', '<em>$1</em>', $content);
    }

    public function getContent($original = true) {
        $content = $this->_get('content');
        if ($original) {
            return $content;
        }
        $operative_phrase = trim($this->_get('ClauseOperativePhrase'));
        if (empty($operative_phrase)) {
            return $content;
        }
        return self::applyOperativePhraseToContent($content, $operative_phrase);
    }

    public function __toString() {
        $content = $this->_get('content');
        if (strlen($content) > 30) {
            $content = substr($content, 0, 27).' ..';
        }
        return $content;
    }

    public function getLatestAdoptedClause() {
        $root_clause_body_id = $this->root_clause_body_id;
        $clause_body_ids = Doctrine_Query::create()
            ->select('cb.id')
            ->from('ClauseBody cb INDEXBY cb.id')
            ->where('cb.root_clause_body_id = ? OR cb.id = ?', array($root_clause_body_id, $root_clause_body_id))
            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        if (empty($clause_body_ids)) {
            return null;
        }

        if (count($clause_body_ids) === 1) {
            return $this;
        }

        $clause_body_ids = array_keys($clause_body_ids);

        return Doctrine_Query::create()
            ->select('c.*')
            ->from('Clause c')
            ->innerJoin('c.Document d')
            ->whereIn('c.clause_body_id', $clause_body_ids)
            ->orderBy('d.adoption_date DESC')
            ->fetchOne();
    }
}
