<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BaseRecord extends sfDoctrineRecord
{
    public function __toString() {
        $string = parent::__toString();
        if (strlen($string) > 35) {
            $string = substr($string, 0, 30).'...';
        }
        return $string;
    }

}
