generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Clause
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          clause_clauses
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        document_id: { label: Document}
        parent_clause_id: { label: Parent clause}
        clause: { label: Parent clause}
        legal_value_id: { label: Legal value}
      list:
        display: [=name, document, adressee, information_type, clause, clause_number]
      filter:  ~
      form:    ~
      edit:
        display: [name, document_id, clause_number, parent_clause_id, information_type, operative_phrase, adressee, relevance, significants, content, created_at, updated_at]
      new:
        display: [name, document_id, clause_number, parent_clause_id, information_type, operative_phrase, adressee, relevance, significants, content]
