generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ClauseClauseRelation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          clause_clause_relation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [Clause, ClauseRelated, type, Author]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
