generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Document
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              document
    plural:                documents
    route_prefix:          document
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        enforcement_date:     {date_format: yyyy/MM/dd}
        adoption_date:       {date_format: yyyy/MM/dd}
      list:
        display: [=code, _parent, _documenttype, _organisation, adoption_date, is_ratified, status, author]
      filter:
        display: ["quick edit search", parent_document_id, documenttype_id, organisation_id, author_id, enforcement_date, adoption_date, is_ratified, status, tags_list]
      form:    ~
      edit:    ~
      new:     ~
