# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  stylesheets:
    - /css/main.css
    - /css/smoothness/jquery-ui-1.8.custom.css

  javascripts:
    - /js/jquery-1.4.2.min.js
    - /js/jquery-ui-1.8.custom.min.js
    - /js/jquery.jqote2.js
    - /js/collapseBoxes.js
    - /js/accordionBoxes.js
    - /js/search.js
    - /js/main.js

  has_layout:     true
  layout:         layout
