generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Documenttype
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          documenttype_documenttypes
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        legal_value_id: { label: "Legal value" }
      list:
        display: [=name, legal_value]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
