<?php

/**
 * Addressee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Addressee extends BaseAddressee
{
	protected static $autoCompletable = array(
    'name' => true,
  );
	
	public function getNumberAddressedClauses()
	{
		return $this->getClauseBodies()->count();
	}
}
