<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddresseeTable extends Doctrine_Table
{
  public function getAllAddressees()
  {
    $q = $this->createQuery('j');
    return $q->fetchArray();
  }
  
  public function retrieveAddresseeIdByLabel($addresseeLabel)
  {
    $addressees = $this->getAllAddressees();
    
    foreach($addressees as $addressee)
    {
      if($addresseeLabel == $addressee['label'])
      {
        return $addressee['id'];
      }
    }
    
    return NULL;
  }
}