<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcelFileTable extends Doctrine_Table
{
  public function retrieveByPk($id)
  {
  	$q = $this->createQuery('e')
      ->where('e.id = ?', $id);
 
    return $q->fetchArray();
  }
}