<?php

/**
 * Organisation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uninformed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Organisation extends BaseOrganisation
{
    protected static $autoCompletable = array(
        'name' => true,
    );

    public function preSave($event) {
        $invoker = $event->getInvoker();
        $slug = $invoker->_get('name');
        $slug = Doctrine_Inflector::urlize($slug);
        $invoker->_set('slug', $slug);
    }

    public function getSlug() {
        return $this->_get('id').'-'.$this->_get('slug');
    }
    
    public function __toString() {
    	return $this->_get('name');
    }
}
