ClauseTag:
  tableName: clause2tag
  columns:
    clause_id:
      type: integer(4)
      primary: true
      unsigned: true
    tag_id:
      type: integer(4)
      primary: true
      unsigned: true
Clause:
  tableName: clauses
  actAs: [Timestampable]
  columns:
    clause_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
    document_id:
      type: integer(4)
      notnull: true
      unsigned: true
    clause_number:
      type: integer(4)
      notnull: true
    parent_clause_id:
      type: integer(4)
      unsigned: true
    information_type: string(45)
    operative_phrase: string(45)
    adressee: string(45)
    relevance: string(45)
    significants: string(45)
    content: string(2147483647)
  relations:
    Document:
      class: Document
      local: document_id
      foreign: document_id
      type: one
    Clause:
      class: Clause
      local: parent_clause_id
      foreign: clause_id
      type: one
    Tags:
      class: Tag
      local: clause_id
      foreign: tag_id
      refClass: ClauseTag
    ParentClauses:
      class: Clause
      local: clause_id
      foreign: parent_clause_id
      type: many
DocumentTag:
  tableName: document2tag
  columns:
    document_id:
      type: integer(4)
      primary: true
      unsigned: true
    tag_id:
      type: integer(4)
      primary: true
      unsigned: true
DocumentRelation:
  tableName: documentrelations
  columns:
    document_id:
      type: integer(4)
      primary: true
      unsigned: true
    related_document_id:
      type: integer(4)
      primary: true
      unsigned: true
    relation_type:
      type: enum(8)
      values: [followup, recalls, report]
      primary: true
  relations:
    Document:
      class: Document
      local: document_id
      foreign: document_id
      type: one
    RelatedDocument:
      class: Document
      local: related_document_id
      foreign: document_id
      type: one
Document:
  tableName: documents
  actAs: [Timestampable]
  columns:
    document_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
    publication_date:
      type: date(25)
      notnull: true
    documenttype_id:
      type: integer(4)
      notnull: true
      unsigned: true
    legal_value:
      type: string(45)
    organisation_id:
      type: integer(4)
      notnull: true
      unsigned: true
    adoption_date: timestamp(25)
    code: string(45)
    min_ratification_count: integer(4)
    preamble: string(2147483647)
  relations:
    Documenttype:
      class: Documenttype
      local: documenttype_id
      foreign: documenttype_id
      type: one
    Organisation:
      local: organisation_id
      foreign: organisation_id
      type: one
    Clauses:
      local: document_id
      foreign: document_id
      type: many
    Tags:
      class: Tag
      local: document_id
      foreign: tag_id
      refClass: DocumentTag
    DocumentRelate:
      class: Documentrelation
      local: document_id
      foreign: document_id
      type: many
    DocumentRelated:
      class: Documentrelation
      local: document_id
      foreign: related_document_id
      type: many
    Votingrecords:
      local: document_id
      foreign: document_id
      type: many
Documenttype:
  tableName: documenttypes
  columns:
    documenttype_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
    legal_value:
      type: string(45)
      notnull: true
  relations:
    Document:
      class: Document
      local: documenttype_id
      foreign: documenttype_id
      type: many
Memberstate:
  tableName: memberstates
  actAs: [Timestampable]
  columns:
    memberstate_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
  relations:
    Organisations:
      class: Organisation
      local: memberstate_id
      foreign: organisation_id
      refClass: MemberstateOrganisation
MemberstateOrganisation:
  tableName: memberstates2organisations
  columns:
    memberstate_id:
      type: integer(4)
      primary: true
      unsigned: true
    organisation_id:
      type: integer(4)
      primary: true
      unsigned: true
Organisation:
  tableName: organisations
  actAs: [Timestampable]
  columns:
    organisation_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
    parent_organisation_id:
      type: integer(4)
      unsigned: true
  relations:
    ParentOrganisation:
      local: parent_organisation_id
      foreign: organisation_id
      type: one
    Documents:
      local: organisation_id
      foreign: organisation_id
      type: many
    Memberstates:
      class: Memberstate
      local: organisation_id
      foreign: memberstate_id
      refClass: MemberstateOrganisation
    ChildOrganisations:
      class: Organisation
      local: organisation_id
      foreign: parent_organisation_id
      type: many
    Votingrecord:
      local: organisation_id
      foreign: memberstate_id
      type: many
TagHierarchieTag:
  tableName: taghierarchie2tag
  columns:
    taghierarchie_id:
      type: integer(4)
      primary: true
      unsigned: true
    tag_id:
      type: integer(4)
      primary: true
      unsigned: true
TagHierarchie:
  tableName: taghierarchies
  columns:
    taghierarchie_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
    hierachie_level:
      type: enum(7)
      values: [area, issue, keyword]
      notnull: true
    parent_taghierarchie_id:
      type: integer(4)
      unsigned: true
  relations:
    ParentTagHierarchie:
      local: parent_taghierarchie_id
      foreign: taghierarchie_id
      type: one
    Tags:
      class: Tag
      local: taghierarchie_id
      foreign: tag_id
      refClass: TagHierarchieTag
    ChildTagHierarchies:
      class: Taghierachie
      local: taghierarchie_id
      foreign: parent_taghierarchie_id
      type: many
TagImplication:
  tableName: tagimplications
  columns:
    tag_id:
      type: integer(4)
      primary: true
      unsigned: true
    implied_tag_id:
      type: integer(4)
      primary: true
      unsigned: true
    implication_type:
      type: enum(8)
      values: [implies, suggests]
      notnull: true
  relations:
    ImpliedTag:
      class: Tag
      local: implied_tag_id
      foreign: tag_id
      type: one
    Tag:
      class: Tag
      local: tag_id
      foreign: tag_id
      type: one
Tag:
  tableName: tags
  actAs: [Timestampable]
  columns:
    tag_id:
      type: integer(4)
      primary: true
      autoincrement: true
      unsigned: true
    name:
      type: string(45)
      notnull: true
    tag_type:
      type: enum(13)
      values: [legal_measure]
  relations:
    Clauses:
      class: Clause
      local: tag_id
      foreign: clause_id
      refClass: ClauseTag
    Documents:
      class: Document
      local: tag_id
      foreign: document_id
      refClass: DocumentTag
    TagHierarchies:
      class: TagHierarchie
      local: tag_id
      foreign: taghierarchie_id
      refClass: TagHierarchieTag
    ImpliedTagImplications:
      class: TagImplication
      local: tag_id
      foreign: implied_tag_id
      type: many
    Tagimplications:
      class: TagImplication
      local: tag_id
      foreign: tag_id
      type: many
Votingrecord:
  tableName: votingrecords
  columns:
    document_id:
      type: integer(4)
      primary: true
      unsigned: true
    memberstate_id:
      type: integer(4)
      primary: true
      unsigned: true
    vote_type:
      type: enum(7)
      values: [signed, agreed, 'no', abstain, missing]
      notnull: true
  relations:
    Document:
      local: document_id
      foreign: document_id
      type: one
    Organisation:
      local: memberstate_id
      foreign: organisation_id
      type: one
