generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Clause
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          clause_clauses
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Clauses
        display: [name]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
