generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DocumentReservation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              documentreservation
    plural:                documentreservations
    route_prefix:          document_reservation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
