generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Memberstate
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          memberstate_memberstates
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: UN Membership States
        display: [name]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:
        title: Edit Memberstate "%%name%%"
      new:
        title: Create new memberstate
