actAs: &actAs
  Timestampable: ~
  Blameable: &Blameable
    default: null
    blameVar: user_id
    listener: BlameableCustomListener
    columns:
      created:
        name: author_id
        length: 4
        options:
          notnull: false
      updated:
        disabled: true
    relations:
      created:
        class: sfGuardUser
        disabled: false
        name: Author
  Versionable:
    actAs:
      Blameable:
        <<: *Blameable

options:
  collation: utf8_general_ci
  charset: utf8
  type: InnoDB

sfGuardUser:
  actAs:
    SoftDelete: ~
    Blameable:
      <<: *Blameable

Import:
  actAs:
    Timestampable: ~
    SoftDelete: ~
    Blameable:
      <<: *Blameable
  inheritance:
    type:          column_aggregation
    extends:       sfGuardUser
  columns:
    excel_file_id:
      type: integer(4)
      notnull: false
  relations:
    ExcelFile:
      class: ExcelFile
      local: excel_file_id
      foreign: id

ExcelFile:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    tag_id:
      type: integer(8)
      notnull: true
    file:
      type: string(255)
      notnull: true
    excel_author_id:
      type: integer(4)
      notnull: false
  relations:
    Tag:
      class: TaggableTag
      local: tag_id
      foreign: id
    sfGuardUser:
      class: sfGuardUser
      local: excel_author_id
      foreign: id

Addressee:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
  relations:
    Clauses:
      class: ClauseBody
      local: id
      foreign: id
      refClass: ClauseAddressee

LegalValue:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    decision_type:
      type: enum
      values: [vote, ratification]
      notnull: false

Organisation:
  actAs:
    <<: *actAs
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: true
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    parent_id:
      type: integer(4)
  relations:
    Parent:
      class: Organisation
      local: parent_id
      foreign: id
      foreignAlias: Suborganisations

DocumentType:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    legalvalue_id:
      type: integer(4)
    rank_priority:
      type: integer(4)
  relations:
    LegalValue:
      class: LegalValue
      local: legalvalue_id
      foreign: id

Document:
  actAs:
    <<: *actAs
    Taggable: ~
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: true
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    publication_date:
      type: date
    adoption_date:
      type: date
      notnull: true
    code:
      type: string(255)
    min_ratification_count:
      type: integer(4)
    is_ratified:
      type: bool
    private_comment:
      type: clob
    public_comment:
      type: clob
    parent_id:
      type: integer(4)
    organisation_id:
      type: integer(4)
    documenttype_id:
      type: integer(4)
    document_url:
      type: string(2505)
    status:
      type: enum
      values: [draft, review, reviewed, inactive, active]
  relations:
    Parent:
      class: Document
      local: parent_id
      foreign: id
      foreignAlias: Subdocuments
    Organisation:
      local: organisation_id
      foreign: id
      foreignAlias: Organisations
    DocumentType:
      local: documenttype_id
      foreign: id
      foreignAlias: Documents
    Tags:
      class: Tag
      local: id
      foreign: id
      foreignAlias: Tags

DocumentDocumentRelation:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    type:
      type: enum
      values: [followup, recalls, closely_related]
      notnull: true
    document_id:
      type: integer(4)
      notnull: true
    related_document_id:
      type: integer(4)
      notnull: true
  relations:
    Document:
      local: document_id
      foreign: id
    DocumentRelated:
      class: Document
      local: related_document_id
      foreign: id
  indexes:
    mapping:
      fields: [document_id, related_document_id, type]
      type: unique

DocumentClauseRelation:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    document_id:
      type: integer(4)
      notnull: true
    related_clause_body_id:
      type: integer(4)
      notnull: true
  relations:
    Document:
      local: document_id
      foreign: id
    ClauseRelated:
      class: ClauseBody
      local: related_clause_body_id
      foreign: id
  indexes:
    mapping:
      fields: [document_id, related_clause_body_id]
      type: unique

Clause:
  actAs:
    <<: *actAs
    Sortable: ~
# we need to somehow inject the document name here and combin it with the position/clause_number* fields
#    Sluggable:
#      unique: true
#      fields: [name]
#      canUpdate: true
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    document_id:
      type: integer(4)
      notnull: true
    clause_body_id:
      type: integer(4)
      notnull: true
    clause_number_information:
      type: string(255)
    clause_number_subparagraph:
      type: string(255)
    private_comment:
      type: clob
  relations:
    Document:
      local: document_id
      foreign: id
      foreignAlias: Clauses
    ClauseBody:
      local: clause_body_id
      foreign: id
  indexes:
    mapping:
      fields: [document_id, clause_body_id]
      type: unique

ClauseBody:
  actAs:
    <<: *actAs
    Taggable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    content:
      type: clob
    information_type_id:
      type: integer(4)
    operative_phrase_id:
      type: integer(4)
    clause_process_id:
      type: integer(4)
    public_comment:
      type: clob
    parent_clause_body_id:
      type: integer(4)
    status:
      type: enum
      values: [draft, in_review, reviewed, inactive, active]
  relations:
    Addressees:
      class: Addressee
      local: id
      foreign: id
      foreignAlias: ClauseAddressee
    Tags:
      class: Tag
      local: id
      foreign: id
      foreignAlias: Tags
    ClauseBodyParent:
      class: ClauseBody
      local: parent_clause_body_id
      foreign: id
      foreignAlias: Subclauses
    ClauseProcess:
      local: clause_process_id
      foreign: id
      foreignAlias: Clauses
    ClauseInformationType:
      local: information_type_id
      foreign: id
      foreignAlias: Clauses
    ClauseOperativePhrase:
      local: operative_phrase_id
      foreign: id
      foreignAlias: Clauses

ClauseReservation:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    clause_body_id:
      type: integer(4)
    country_id:
      type: integer(4)
    reservation:
      type: clob
  relations:
    Clause:
      class: ClauseBody
      local: clause_body_id
      foreign: id
    Country:
      local: country_id
      foreign: id
      foreignAlias: Countries
  indexes:
    mapping:
      fields: [clause_body_id, country_id]
      type: unique

ClauseProcess:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true

ClauseOperativePhrase:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true

ClauseInformationType:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true

TagImplication:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    implication_type:
      type: enum
      values: ['implies', 'suggests']
      notnull: true
    tag_id:
      type: integer(8)
      notnull: true
    implied_tag_id:
      type: integer(8)
      notnull: true
  relations:
    Tag:
      class: TaggableTag
      local: tag_id
      foreign: id
      alias: Tag
    ImpliedTag:
      class: TaggableTag
      local: implied_tag_id
      foreign: id
      alias: ImpliedTag
  indexes:
    mapping:
      fields: [tag_id, implied_tag_id]
      type: unique

Country:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true

CountryOrganisation:
  actAs:
    <<: *actAs
    Temporal:
      unique_fields: [document_id, country_id]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    country_id:
      type: integer(4)
      notnull: true
    organisation_id:
      type: integer(4)
      notnull: true
  relations:
    Country:
      local: country_id
      foreign: id
      foreignAlias: Organisations
    Organisation:
      local: organisation_id
      foreign: id
      foreignAlias: Countries

Vote:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    type:
      type: enum
      values: [signed, agreed, 'no', abstain, missing]
    document_id:
      type: integer(4)
      notnull: true
    country_id:
      type: integer(4)
      notnull: true
  relations:
    Document:
      local: document_id
      foreign: id
      foreignAlias: Votes
    Country:
      local: country_id
      foreign: id
      foreignAlias: Votes
  indexes:
    mapping:
      fields: [document_id, country_id]
      type: unique

ClauseAddressee:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    clause_body_id:
      type: integer(4)
      notnull: true
    addressee_id:
      type: integer(4)
      notnull: true
  indexes:
    mapping:
      fields: [clause_body_id, addressee_id]
      type: unique
