actAs: [Timestampable]

options:
  collation: utf8_general_ci
  charset: utf8
  type: InnoDB

Addressee:
  tableName: addressees
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
  relations:
    Clauses:
      class: Clause
      local: id
      foreign: clause_id
      refClass: ClauseAddressee

LegalValue:
  tableName: legalvalues
  columns:
    legalvalue_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true

Organisation:
  tableName: organisations
  columns:
    organisation_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    parent_id:
      type: integer
  relations:
    Parent:
      class: Organisation
      local: parent_id
      foreign: organisation_id
      foreignAlias: Suborganisations

DocumentType:
  tableName: documenttypes
  columns:
    documenttype_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    legalvalue_id:
      type: integer
  relations:
    LegalValue:
      class: LegalValue
      local: legalvalue_id
      foreign: legalvalue_id

Document:
  tableName: documents
  columns:
    document_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    publication_date:
      type: date
    adoption_date:
      type: date
      notnull: true
    code:
      type: string(255)
    min_ratification_count:
      type: integer(4)
    preamble:
      type: string
    parent_id:
      type: integer
    organisation_id:
      type: integer
    documenttype_id:
      type: integer
    documentURL:
      type: string(255)
  relations:
    Parent:
      class: Document
      local: parent_id
      foreign: document_id
      foreignAlias: Subdocuments
    Organisation:
      local: organisation_id
      foreign: organisation_id
      foreignAlias: Organisations
    DocumentType:
      local: documenttype_id
      foreign: documenttype_id
      foreignAlias: Documents
    Tags:
      class: Tag
      local: document_id
      foreign: tag_id
      refClass: DocumentTag
      
DocumentRelation:
  tableName: documentrelations
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    relation_type:
      type: enum
      values: [followup, recalls, report]
      notnull: true
    document_left_hand:
      type: integer
      notnull: true
    document_right_hand:
      type: integer
      notnull: true
  relations:
    Document:
      local: document_left_hand
      foreign: document_id
    Document:
      local: document_right_hand
      foreign: document_id

Clause:
  tableName: clauses
  columns:
    clause_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    clause_process:
      type: integer
    clause_number:
      type: string(255)
      notnull: true
    information_type:
      type: integer
    operative_phrase:
      type: integer
    relevance:
      type: string(255)
    significants:
      type: string(255)
    content:
      type: string
    parent_id:
      type: integer
    document_id:
      type: integer
  relations:
    Parent:
      class: Clause
      local: parent_id
      foreign: clause_id
      foreignAlias: Subclauses
    ClauseProcess:
      local: clause_process
      foreign: id
      foreignAlias: Clauses
    ClauseInformationType:
      local: information_type
      foreign: id
      foreignAlias: Clauses
    ClauseOperativePhrase:
      local: operative_phrase
      foreign: id
      foreignAlias: Clauses
    Document:
      local: document_id
      foreign: document_id
      foreignAlias: Clauses
    Addressees:
      class: Addressee
      local: clause_id
      foreign: id
      foreignAlias: ClauseAddressee
    Tags:
      class: Tag
      local: clause_id
      foreign: tag_id
      refClass: ClauseTag

ClauseProcess:
  tableName: clauseprocesses
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    label:
      type: string(255)
      notnull: true

ClauseOperativePhrase:
  tableName: clauseoperativephrases
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    label:
      type: string(255)
      notnull: true

ClauseInformationType:
  tableName: clauseinformationtypes
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    label:
      type: string(255)
      notnull: true

Tag:
  tableName: tags
  columns:
    tag_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    tag_type:
      type: enum
      values: ['', legal_measure]
      notnull: true
  relations:
    Clauses:
      class: Clause
      local: tag_id
      foreign: clause_id
      refClass: ClauseTag
    Documents:
      class: Document
      local: tag_id
      foreign: document_id
      refClass: DocumentTag
    TagHierarchies:
      class: TagHierarchie
      local: tag_id
      foreign: taghierarchie_id
      refClass: TagHierarchieTag

TagImplication:
  tableName: tagimplications
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    implication_type:
      type: enum
      values: ['implies', 'suggests']
      notnull: true
    tag_left_hand:
      type: integer
      notnull: true
    tag_right_hand:
      type: integer
      notnull: true
  relations:
    Tag:
      local: tag_left_hand
      foreign: tag_id
    Tag:
      local: tag_right_hand
      foreign: tag_id

TagHierarchie:
  tableName: taghierarchies
  columns:
    taghierarchie_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    hierarchie_level:
      type: enum
      values: ['area', 'issue', 'keyword']
    parent_id:
      type: integer
  relations:
    Parent:
      class: TagHierarchie
      local: parent_id
      foreign: taghierarchie_id
      foreignAlias: SubHierarchies
    Tags:
      class: Tag
      local: taghierarchie_id
      foreign: tag_id
      refClass: TagHierarchieTag

Memberstate:
  tableName: memberstates
  columns:
    memberstate_id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)

MemberstateOrganisation:
  tableName: memberstatesorganisations
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    join_date:
      type: date
      notnull: true
    leave_date:
      type: date
    memberstate_id:
      type: integer
    organisation_id:
      type: integer
  relations:
    Memberstate:
      local: memberstate_id
      foreign: memberstate_id
      foreignAlias: Organisations
    Organisation:
      local: organisation_id
      foreign: organisation_id
      foreignAlias: Memberstates

Vote:
  tableName: votes
  columns:
    vote_id:
      type: integer
      primary: true
      autoincrement: true
    label:
      type: enum
      values: [signed, agreed, 'no', abstain, missing]
    document_id:
      type: integer
    memberstate_id:
      type: integer
  relations:
    Document:
      local: document_id
      foreign: document_id
      foreignAlias: Votes
    Memberstate:
      local: memberstate_id
      foreign: memberstate_id
      foreignAlias: Votes

ClauseAddressee:
  columns:
    clause_id:
      type: integer
      primary: true
    addressee_id:
      type: integer
      primary: true

ClauseTag:
  columns:
    clause_id:
      type: integer
      primary: true
    tag_id:
      type: integer
      primary: true

DocumentTag:
  columns:
    document_id:
      type: integer
      primary: true
    tag_id:
      type: integer
      primary: true

TagHierarchieTag:
  columns:
    taghierarchie_id:
      type: integer
      primary: true
    tag_id:
      type: integer
      primary: true