# Define all the models in your project that you want indexed.

ClauseBody:
  index:
    cultures: [en]
    encoding: UTF-8
    host: 127.0.0.1
    port: 8983
    base_url: "/solr"
  models:
    ClauseBody:
      title: title
      description: content
      route: clause/%slug%
      fields:
        id:
          type: int
          indexed: false
          stored: true
          required: true
          alias: getId
        slug:
          type: string
          indexed: false
          stored: true
          required: true
          alias: getSlug
        root_clause_body_id:
          type: int
          stored: true
          required: true
          alias: getRootClauseBodyId
        document_id:
          type: int
          stored: true
          required: true
          alias: getDocumentId
        title:
          type: string
          alias: getTitle
        adoption_date:
          type: tdate
          stored: false
          alias: getAdoptionDate
        tags:
          type: text
          stored: false
          multiValued: true
          alias: getTagNames
        content:
          type: text
          stored: false
          alias: getContent
        clause_operative_phrase:
          type: text
          stored: false
          alias: getClauseOperativePhrase
        clause_information_type:
          type: text
          stored: false
          alias: getClauseInformationType
        clause_process:
          type: text
          stored: false
          alias: getClauseProcess
